/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codewars;

import java.util.*;
import java.util.stream.Collectors;

public class Inspector {

  private static final Set<String> COUNTRY_NAMES = Set.of(
    "Arstotzka", "Antegria", "Impor", "Kolechia", "Obristan", "Republia", "United Federation"
  );

  private final Set<String> allowedCountries = new HashSet<>();
  private final Set<Rule> vaccineRules = new HashSet<>();
  private final Set<Rule> documentRules = new HashSet<>();
  private String wantedCriminal;

  public void receiveBulletin(String bulletin) {
    // Reset wanted criminal each day
    wantedCriminal = null;

    List<String> rules = List.of(bulletin.split("/n"));
    processRules(rules);
  }

  private void processRules(List<String> rulesList) {
    for (String rule: rulesList) {
      if (rule.startsWith("Allow") || rule.startsWith("Deny")) {
        processNationRule(rule);
      } else if (rule.startsWith("Wanted")) {
        processCriminalRule(rule);
      } else if (rule.contains("vaccination")) {
        processVaccineRule(rule);
      } else {
        processDocumentRule(rule);
      }
    }
  }

  private void processNationRule(String rule) {
    String[] countries = rule.substring(rule.indexOf("of") + 3).split(",");
    List<String> countryNames = Arrays.stream(countries).map(String::trim).collect(Collectors.toList());
    if (rule.startsWith("Allow")) {
      allowedCountries.addAll(countryNames);
    } else {
      countryNames.forEach(allowedCountries::remove);
    }
  }

  private void processCriminalRule(String rule) {
    wantedCriminal = rule.substring(rule.indexOf(":") + 2);
  }

  private void processVaccineRule(String rule) {
    String[] words = rule.split(" ");
    String vaccineName = words[words.length - 2];
    if (rule.startsWith("Entrants") || rule.startsWith("Foreigners") || rule.startsWith("Workers")) {
      // General rule
      addGeneralVaccineRule(rule, vaccineName);
    } else {
      // Per country rule
      addPerCountryVaccineRule(rule, vaccineName);
    }
  }

  private void addGeneralVaccineRule(String rule, String vaccineName) {
    // Determine the countries this general rule applies to
    boolean isForWorkers = false;
    Set<String> countries;
    if (rule.startsWith("Entrants")) {
      countries = COUNTRY_NAMES;
    } else if (rule.startsWith("Foreigners")) {
      countries = new HashSet<>(COUNTRY_NAMES);
      countries.remove("Arstotzka");
    } else {
      isForWorkers = true;
      countries = getCountriesForRule(rule);
    }

    Rule vaccineRule = new Rule(vaccineName, countries);
    if (vaccineRules.contains(vaccineRule)) {
      // Update existing rule
      if (rule.contains("no")) {
        vaccineRules.remove(vaccineRule);
      } else {
        vaccineRules.stream().filter(r -> r.name.equals(vaccineName)).forEach(r -> r.countries.addAll(COUNTRY_NAMES));
      }
    } else if (!rule.contains("no")) {
      // Add a new rule
      vaccineRules.add(vaccineRule);
    }
  }

  private void addPerCountryVaccineRule(String rule, String vaccineName) {
    Set<String> countries = getCountriesForRule(rule);
    Rule vaccineRule = new Rule(vaccineName, countries);
    if (vaccineRules.contains(vaccineRule)) {
      // Update existing rule
      vaccineRules.stream().filter(r -> r.name.equals(vaccineName)).forEach(r -> {
        if (rule.contains("no")) {
          r.countries.removeAll(countries);
        } else {
          r.countries.addAll(countries);
        }
      });
    } else if (!rule.contains("no")) {
      // Add a new rule
      vaccineRules.add(new Rule(vaccineName, countries));
    }
  }

  private Set<String> getCountriesForRule(String rule) {
    return Arrays.stream(rule.split(" ")).filter(COUNTRY_NAMES::contains).collect(Collectors.toSet());
  }

  private void processDocumentRule(String rule) {

  }

  public String inspect(Map<String, String> person) {
    // Your code here
    return "";
  }
}

class Rule {
  public final String name;
  public Set<String> countries;
  public boolean isForWorkers;

  public Rule(String name, Set<String> countries) {
    this.name = name;
    this.countries = countries;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    Rule that = (Rule) o;
    return name.equals(that.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name);
  }
}
